let data=loadData();
const $=id=>document.getElementById(id);
function refresh(){data=loadData();heroKicker.value=data.hero.kicker;heroTitleInput.value=data.hero.title;heroSubtitleInput.value=data.hero.subtitle;heroImageInput.value=data.hero.image;articlesAdmin.innerHTML='<table class="data-table"><tr><th>Título</th><th>Categoria</th><th>Ações</th></tr>'+data.articles.map(a=>`<tr><td>${esc(a.title)}</td><td>${esc(a.category)}</td><td><button class="btn" onclick="editArticle(${a.id})">Editar</button> <button class="btn danger" onclick="deleteArticle(${a.id})">Excluir</button></td></tr>`).join('')+'</table>';eventsAdmin.innerHTML='<table class="data-table"><tr><th>Data</th><th>Evento</th><th>Ações</th></tr>'+data.events.map(e=>`<tr><td>${e.date}</td><td>${esc(e.name)}</td><td><button class="btn" onclick="editEvent(${e.id})">Editar</button> <button class="btn danger" onclick="deleteEvent(${e.id})">Excluir</button></td></tr>`).join('')+'</table>';rankingAdmin.innerHTML='<table class="data-table"><tr><th>Nome</th><th>Categoria</th><th>Votos</th></tr>'+data.ranking.map(r=>`<tr><td>${esc(r.name)}</td><td>${esc(r.category)}</td><td><input type="number" value="${r.votes}" onchange="updateVotes(${r.id},this.value)"></td></tr>`).join('')+'</table>'}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.admin-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active')});
heroForm.onsubmit=e=>{e.preventDefault();data.hero={...data.hero,kicker:heroKicker.value,title:heroTitleInput.value,subtitle:heroSubtitleInput.value,image:heroImageInput.value||'assets/hero.svg'};saveData(data);alert('Home atualizada');refresh()};
listenHero.onclick=()=>speakText(heroTitleInput.value+'. '+heroSubtitleInput.value);
articleForm.onsubmit=e=>{e.preventDefault();const id=Number(articleId.value)||Date.now();const item={id,category:articleCategory.value||'GERAL',author:articleAuthor.value||'Equipe TOPS',title:articleTitle.value,summary:articleSummary.value,content:articleContent.value,image:'assets/hero.svg'};const i=data.articles.findIndex(x=>x.id===id);if(i>=0)data.articles[i]=item;else data.articles.push(item);saveData(data);articleForm.reset();refresh()};
function editArticle(id){const a=data.articles.find(x=>x.id===id);articleId.value=a.id;articleCategory.value=a.category;articleAuthor.value=a.author;articleTitle.value=a.title;articleSummary.value=a.summary;articleContent.value=a.content;scrollTo({top:0,behavior:'smooth'})}
function deleteArticle(id){if(confirm('Excluir matéria?')){data.articles=data.articles.filter(x=>x.id!==id);saveData(data);refresh()}}
eventForm.onsubmit=e=>{e.preventDefault();const id=Number(eventId.value)||Date.now();const item={id,date:eventDate.value,name:eventName.value,location:eventLocation.value};const i=data.events.findIndex(x=>x.id===id);if(i>=0)data.events[i]=item;else data.events.push(item);saveData(data);eventForm.reset();refresh()};
function editEvent(id){const e=data.events.find(x=>x.id===id);eventId.value=e.id;eventDate.value=e.date;eventName.value=e.name;eventLocation.value=e.location}
function deleteEvent(id){if(confirm('Excluir evento?')){data.events=data.events.filter(x=>x.id!==id);saveData(data);refresh()}}
function updateVotes(id,value){const r=data.ranking.find(x=>x.id===id);r.votes=Number(value)||0;saveData(data)}
resetData.onclick=()=>{if(confirm('Restaurar dados?')){localStorage.removeItem('topsPlatformData');location.reload()}};
refresh();