let data=loadData();
const $=id=>document.getElementById(id);
const notify=msg=>{const el=$('saveStatus');if(el){el.textContent=msg;setTimeout(()=>el.textContent='Alterações salvas neste dispositivo',1800)}};
const fileToDataUrl=file=>new Promise((resolve,reject)=>{if(!file)return resolve('');const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)});
function ensureShape(){data.interview??={name:'Isabella Fiore',kicker:'PERSONAGEM FICTÍCIA',title:'Carreira, imagem e próximos projetos',summary:'Uma conversa inspiradora sobre identidade, trabalho, presença e o futuro da moda.',image:'assets/modelo-isabella.svg',articleId:2};data.media??=[];data.settings??={footerText:'TOPS Revista Digital · Moda, beleza e cultura',instagram:'@topsrevista',contact:'contato@topsrevista.com',menuItems:['Início','Notícias','Moda','Entrevistas','Eventos','Ranking','Revista 3D'],gold:'#d4af37',background:'#050505',titleScale:'normal',cardRatio:'landscape'};data.hero.buttonText??='Ler matéria completa';data.ranking=data.ranking.map(r=>({...r,image:r.image||'assets/modelo-beatriz.svg'}));}
function save(){ensureShape();saveData(data);notify('Salvo com sucesso');refreshDashboard();}
function refreshDashboard(){if(!$('dashboardCards'))return;$('dashboardCards').innerHTML=[['Matérias',data.articles.length],['Imagens',data.media.length],['Eventos',data.events.length],['Participantes',data.ranking.length],['Páginas da revista',data.magazine.length]].map(([l,v])=>`<div class="metric-admin"><span>${esc(l)}</span><strong>${v}</strong></div>`).join('')}
function refresh(){data=loadData();ensureShape();
heroKicker.value=data.hero.kicker||'';heroTitleInput.value=data.hero.title||'';heroSubtitleInput.value=data.hero.subtitle||'';heroImageInput.value=data.hero.image||'';heroButtonText.value=data.hero.buttonText||'Ler matéria completa';heroPreview.src=data.hero.image||'';
interviewName.value=data.interview.name||'';interviewKicker.value=data.interview.kicker||'';interviewTitle.value=data.interview.title||'';interviewSummary.value=data.interview.summary||'';interviewImage.value=data.interview.image||'';
footerText.value=data.settings.footerText||'';instagramText.value=data.settings.instagram||'';contactText.value=data.settings.contact||'';menuItems.value=(data.settings.menuItems||[]).join(', ');goldColor.value=data.settings.gold||'#d4af37';backgroundColor.value=data.settings.background||'#050505';titleScale.value=data.settings.titleScale||'normal';cardRatio.value=data.settings.cardRatio||'landscape';
articlesAdmin.innerHTML='<table class="data-table"><tr><th>Imagem</th><th>Título</th><th>Categoria</th><th>Ações</th></tr>'+data.articles.map(a=>`<tr><td><img class="table-thumb" src="${a.image}"></td><td>${esc(a.title)}</td><td>${esc(a.category)}</td><td><button class="btn mini" onclick="editArticle(${a.id})">Editar</button> <button class="btn danger mini" onclick="deleteArticle(${a.id})">Excluir</button></td></tr>`).join('')+'</table>';
eventsAdmin.innerHTML='<table class="data-table"><tr><th>Data</th><th>Evento</th><th>Local</th><th>Ações</th></tr>'+data.events.map(e=>`<tr><td>${e.date}</td><td>${esc(e.name)}</td><td>${esc(e.location)}</td><td><button class="btn mini" onclick="editEvent(${e.id})">Editar</button> <button class="btn danger mini" onclick="deleteEvent(${e.id})">Excluir</button></td></tr>`).join('')+'</table>';
rankingAdmin.innerHTML='<table class="data-table"><tr><th>Nome</th><th>Categoria</th><th>Votos</th><th>Ações</th></tr>'+data.ranking.map(r=>`<tr><td>${esc(r.name)}</td><td>${esc(r.category)}</td><td>${Number(r.votes).toLocaleString('pt-BR')}</td><td><button class="btn mini" onclick="editRanking(${r.id})">Editar</button> <button class="btn danger mini" onclick="deleteRanking(${r.id})">Excluir</button></td></tr>`).join('')+'</table>';
mediaGrid.innerHTML=data.media.length?data.media.map((m,i)=>`<article class="media-card"><img src="${m.src}" alt="${esc(m.name)}"><strong>${esc(m.name)}</strong><div class="actions"><button class="btn mini" onclick="copyMedia(${i})">Copiar referência</button><button class="btn danger mini" onclick="deleteMedia(${i})">Excluir</button></div></article>`).join(''):'<p class="muted">Nenhuma imagem enviada ainda.</p>';
magazineAdmin.innerHTML=data.magazine.map((p,i)=>`<article class="magazine-admin-item"><img src="${p.image}"><div><strong>${i+1}. ${esc(p.title)}</strong><small>${p.type==='cover'?'Capa':'Página interna'}</small></div><div class="actions"><button class="btn mini" onclick="moveMagazine(${i},-1)">↑</button><button class="btn mini" onclick="moveMagazine(${i},1)">↓</button><button class="btn mini" onclick="editMagazine(${i})">Editar</button><button class="btn danger mini" onclick="deleteMagazine(${i})">Excluir</button></div></article>`).join('');
backupText.value=JSON.stringify(data,null,2);refreshDashboard();}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.admin-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active');window.scrollTo({top:0,behavior:'smooth'})});
heroImageInput.oninput=()=>heroPreview.src=heroImageInput.value;
heroImageFile.onchange=async()=>{const src=await fileToDataUrl(heroImageFile.files[0]);if(src){heroImageInput.value=src;heroPreview.src=src}};
heroForm.onsubmit=e=>{e.preventDefault();data.hero={...data.hero,kicker:heroKicker.value,title:heroTitleInput.value,subtitle:heroSubtitleInput.value,image:heroImageInput.value,buttonText:heroButtonText.value};save();refresh()};
listenHero.onclick=()=>speakText(heroTitleInput.value+'. '+heroSubtitleInput.value);
articleImageFile.onchange=async()=>{const src=await fileToDataUrl(articleImageFile.files[0]);if(src)articleImage.value=src};
articleForm.onsubmit=e=>{e.preventDefault();const id=Number(articleId.value)||Date.now();const item={id,category:articleCategory.value||'GERAL',author:articleAuthor.value||'Equipe TOPS',title:articleTitle.value,summary:articleSummary.value,content:articleContent.value,image:articleImage.value||data.hero.image};const i=data.articles.findIndex(x=>x.id===id);if(i>=0)data.articles[i]=item;else data.articles.push(item);save();articleForm.reset();refresh()};
clearArticle.onclick=()=>articleForm.reset();
function editArticle(id){const a=data.articles.find(x=>x.id===id);articleId.value=a.id;articleCategory.value=a.category;articleAuthor.value=a.author;articleTitle.value=a.title;articleSummary.value=a.summary;articleContent.value=a.content;articleImage.value=a.image;document.querySelector('[data-tab="articles"]').click()}
function deleteArticle(id){if(confirm('Excluir matéria?')){data.articles=data.articles.filter(x=>x.id!==id);save();refresh()}}
mediaForm.onsubmit=async e=>{e.preventDefault();const src=await fileToDataUrl(mediaFile.files[0]);if(!src)return alert('Selecione uma imagem');data.media.push({name:mediaName.value||`Imagem ${data.media.length+1}`,src});save();mediaForm.reset();refresh()};
function copyMedia(i){const ref=data.media[i].src;navigator.clipboard?.writeText(ref);alert('Referência copiada. Cole no campo de imagem desejado.')}
function deleteMedia(i){if(confirm('Excluir imagem da biblioteca?')){data.media.splice(i,1);save();refresh()}}
interviewImageFile.onchange=async()=>{const src=await fileToDataUrl(interviewImageFile.files[0]);if(src)interviewImage.value=src};
interviewForm.onsubmit=e=>{e.preventDefault();data.interview={...data.interview,name:interviewName.value,kicker:interviewKicker.value,title:interviewTitle.value,summary:interviewSummary.value,image:interviewImage.value};save();refresh()};
eventForm.onsubmit=e=>{e.preventDefault();const id=Number(eventId.value)||Date.now();const item={id,date:eventDate.value,name:eventName.value,location:eventLocation.value};const i=data.events.findIndex(x=>x.id===id);if(i>=0)data.events[i]=item;else data.events.push(item);save();eventForm.reset();refresh()};clearEvent.onclick=()=>eventForm.reset();
function editEvent(id){const e=data.events.find(x=>x.id===id);eventId.value=e.id;eventDate.value=e.date;eventName.value=e.name;eventLocation.value=e.location;document.querySelector('[data-tab="events"]').click()}
function deleteEvent(id){if(confirm('Excluir evento?')){data.events=data.events.filter(x=>x.id!==id);save();refresh()}}
rankingForm.onsubmit=e=>{e.preventDefault();const id=Number(rankingId.value)||Date.now();const item={id,name:rankingName.value,category:rankingCategory.value,votes:Number(rankingVotes.value)||0,image:rankingImage.value||data.hero.image};const i=data.ranking.findIndex(x=>x.id===id);if(i>=0)data.ranking[i]=item;else data.ranking.push(item);save();rankingForm.reset();refresh()};
function editRanking(id){const r=data.ranking.find(x=>x.id===id);rankingId.value=r.id;rankingName.value=r.name;rankingCategory.value=r.category;rankingVotes.value=r.votes;rankingImage.value=r.image||'';document.querySelector('[data-tab="ranking"]').click()}
function deleteRanking(id){if(confirm('Excluir participante?')){data.ranking=data.ranking.filter(x=>x.id!==id);save();refresh()}}
magazineImageFile.onchange=async()=>{const src=await fileToDataUrl(magazineImageFile.files[0]);if(src)magazineImage.value=src};
magazineForm.onsubmit=e=>{e.preventDefault();const index=magazineIndex.value===''?-1:Number(magazineIndex.value);const item={title:magazineTitle.value,image:magazineImage.value,type:magazineType.value};if(item.type==='cover')item.subtitle=magazineText.value;else item.text=magazineText.value;if(index>=0)data.magazine[index]=item;else data.magazine.push(item);save();magazineForm.reset();magazineIndex.value='';refresh()};clearMagazine.onclick=()=>{magazineForm.reset();magazineIndex.value=''};
function editMagazine(i){const p=data.magazine[i];magazineIndex.value=i;magazineTitle.value=p.title;magazineType.value=p.type||'page';magazineText.value=p.subtitle||p.text||'';magazineImage.value=p.image;document.querySelector('[data-tab="magazine"]').click()}
function deleteMagazine(i){if(confirm('Excluir página?')){data.magazine.splice(i,1);save();refresh()}}
function moveMagazine(i,dir){const j=i+dir;if(j<0||j>=data.magazine.length)return;[data.magazine[i],data.magazine[j]]=[data.magazine[j],data.magazine[i]];save();refresh()}
navigationForm.onsubmit=e=>{e.preventDefault();data.settings.footerText=footerText.value;data.settings.instagram=instagramText.value;data.settings.contact=contactText.value;data.settings.menuItems=menuItems.value.split(',').map(x=>x.trim()).filter(Boolean);save();refresh()};
appearanceForm.onsubmit=e=>{e.preventDefault();data.settings.gold=goldColor.value;data.settings.background=backgroundColor.value;data.settings.titleScale=titleScale.value;data.settings.cardRatio=cardRatio.value;save();refresh()};
exportData.onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='tops-backup.json';a.click();URL.revokeObjectURL(a.href)};
importData.onchange=async()=>{try{const obj=JSON.parse(await importData.files[0].text());data=obj;save();refresh();alert('Backup importado')}catch{alert('Arquivo inválido')}};
resetData.onclick=()=>{if(confirm('Restaurar todos os dados da demonstração?')){localStorage.removeItem('topsPlatformData');location.reload()}};
refresh();