const DEFAULT_DATA={hero:{kicker:'CAPA DA SEMANA',title:'A NOVA FORÇA DA MODA É AGORA!',subtitle:'Conheça a trajetória da personalidade que vem conquistando espaço, audiência e o coração do público.',image:'assets/hero.svg',articleId:1},articles:[{id:1,category:'MODA',title:'A nova força da moda é agora',summary:'Valentina Noir apresenta uma estética forte e contemporânea na edição piloto da TOPS.',author:'Equipe TOPS',image:'assets/hero.svg',content:'A TOPS nasce para apresentar moda, cultura, imagem e comportamento com uma linguagem sofisticada.\n\nA proposta editorial valoriza histórias selecionadas, fotografias com respiro e experiências que ultrapassam o formato de um portal comum.'},{id:2,category:'ENTREVISTA',title:'Por trás da imagem: carreira, criatividade e futuro',summary:'Uma conversa sobre identidade, trabalho e novos projetos.',author:'Redação TOPS',image:'assets/hero.svg',content:'Nesta entrevista, falamos sobre construção de imagem, disciplina e intenção.'},{id:3,category:'EVENTOS',title:'Noite de gala movimenta a nova cena',summary:'Os principais momentos, convidados e produções da noite.',author:'Equipe TOPS',image:'assets/hero.svg',content:'Uma noite pensada para unir moda, música e experiências de marca.'}],events:[{id:1,date:'2026-08-24',name:'Festa Black & Gold',location:'Clube Sunset · SP'},{id:2,date:'2026-08-31',name:'Desfile Fashion TOP',location:'Centro de Eventos · RJ'},{id:3,date:'2026-09-07',name:'Lançamento Collection',location:'Galeria Club · BH'}],ranking:[{id:1,name:'Valentina Noir',category:'Modelo fictícia',votes:12540},{id:2,name:'Lucas Vibe',category:'Influenciador',votes:8765},{id:3,name:'Gabriela Luz',category:'Atriz',votes:5432}],magazine:[{title:'PODER & ELEGÂNCIA',subtitle:'A nova era da mulher moderna',image:'assets/hero.svg',type:'cover'},{title:'A FORÇA QUE NOS MOVE',text:'Identidade, autenticidade e presença definem a nova geração TOPS.',image:'assets/hero.svg'},{title:'MODA COM INTENÇÃO',text:'Tendências, formas e peças que transformam referência em identidade.',image:'assets/hero.svg'},{title:'CONVERSA TOPS',text:'Uma entrevista sobre carreira, futuro e imagem.',image:'assets/hero.svg'},{title:'BELEZA É PRESENÇA',text:'Cuidados e escolhas que valorizam a essência.',image:'assets/hero.svg'},{title:'LIFESTYLE & EVENTOS',text:'Experiências e lançamentos que movimentam a cena.',image:'assets/hero.svg'}]};
function loadData(){const raw=localStorage.getItem('topsPlatformData');if(!raw){localStorage.setItem('topsPlatformData',JSON.stringify(DEFAULT_DATA));return structuredClone(DEFAULT_DATA)}try{return JSON.parse(raw)}catch{return structuredClone(DEFAULT_DATA)}}
function saveData(data){localStorage.setItem('topsPlatformData',JSON.stringify(data))}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
let speech;
function speakText(text){stopSpeech();speech=new SpeechSynthesisUtterance(text);speech.lang='pt-BR';speech.rate=Number(document.getElementById('speechRate')?.value||1);speechSynthesis.speak(speech)}
function pauseSpeech(){speechSynthesis.pause()}function resumeSpeech(){speechSynthesis.resume()}function stopSpeech(){speechSynthesis.cancel()}
let currentPage=0,magazine=[];
function renderBook(){const book=document.getElementById('book');if(!book)return;book.innerHTML='';const left=magazine[currentPage],right=magazine[currentPage+1];if(left)book.appendChild(pageEl(left,'left'));if(right)book.appendChild(pageEl(right,'right'));document.getElementById('pageCount').textContent=`${Math.min(currentPage+1,magazine.length)}–${Math.min(currentPage+2,magazine.length)} / ${magazine.length}`}
function pageEl(p,side){const el=document.createElement('div');el.className='page-sheet '+side;el.innerHTML=p.type==='cover'?`<div class="mag-page cover"><img src="${p.image}"><div class="cover-shade"><img class="cover-logo" src="assets/tops-logo.svg"><div><div class="cover-title">${esc(p.title)}</div><p>${esc(p.subtitle)}</p></div></div></div>`:`<div class="mag-page"><span class="kicker">TOPS REVISTA</span><h3>${esc(p.title)}</h3><p>${esc(p.text||'')}</p><img class="inner" src="${p.image}"></div>`;return el}
function nextPage(){if(currentPage<magazine.length-2){currentPage+=2;renderBook()}}function prevPage(){if(currentPage>0){currentPage-=2;renderBook()}}
document.addEventListener('keydown',e=>{if(e.key==='ArrowRight')nextPage();if(e.key==='ArrowLeft')prevPage()});
document.addEventListener('DOMContentLoaded',()=>{const d=loadData();magazine=d.magazine||[];if(document.getElementById('heroTitle')){heroKickerView.textContent=d.hero.kicker;heroTitle.textContent=d.hero.title;heroSubtitle.textContent=d.hero.subtitle;heroImage.src=d.hero.image;articleCards.innerHTML=d.articles.map(a=>`<article class="card"><img src="${a.image}"><div class="card-body"><small>${esc(a.category)}</small><h3>${esc(a.title)}</h3><p>${esc(a.summary)}</p><a class="btn" href="materia.html?id=${a.id}">Ler matéria</a></div></article>`).join('');rankingList.innerHTML=d.ranking.sort((a,b)=>b.votes-a.votes).map((r,i)=>`<div class="ranking-item"><b>${String(i+1).padStart(2,'0')}</b><div><strong>${esc(r.name)}</strong><small>${esc(r.category)}</small></div><em>${r.votes.toLocaleString('pt-BR')} votos</em></div>`).join('');eventsList.innerHTML=d.events.map(e=>`<div class="event-item"><div class="event-date">${new Date(e.date+'T12:00:00').toLocaleDateString('pt-BR',{day:'2-digit',month:'short'})}</div><div><strong>${esc(e.name)}</strong><p>${esc(e.location)}</p></div></div>`).join('');renderBook()}});