const pages=[
{label:'CAPA',title:'Talentos que inspiram',image:'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=88',text:'DEU CAPA. — edição de estreia.'},
{label:'EDITORIAL',title:'A força de uma imagem',image:'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1200&q=88',text:'Histórias, marcas e pessoas transformadas em presença editorial.'},
{label:'MODA',title:'Identidade em movimento',image:'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=1200&q=88',text:'Estilo, autoria e novas referências em evidência.'},
{label:'RETRATO',title:'Quem cria também inspira',image:'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=1200&q=88',text:'Retratos de quem movimenta ideias e comunidades.'},
{label:'EVENTOS',title:'Momentos inesquecíveis',image:'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=88',text:'Acontecimentos que merecem virar memória.'},
{label:'AGENDA',title:'A cidade acontece aqui',image:'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1200&q=88',text:'Lançamentos, encontros e experiências selecionadas.'},
{label:'NEGÓCIOS',title:'Marcas com propósito',image:'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=88',text:'Projetos locais com imagem, presença e intenção.'},
{label:'CONEXÕES',title:'Pessoas movem ideias',image:'https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1200&q=88',text:'Até a próxima edição.'}
];
const articles={
negocios:{category:'DEU NEGÓCIO',time:'5 MIN DE LEITURA',title:'Marcas locais que transformam criatividade em movimento',subtitle:'Quando identidade, presença e consistência trabalham juntas, pequenos negócios começam a ocupar espaços maiores.',author:'Equipe DEU CAPA.',image:'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1600&q=90',body:['Uma marca forte não começa pelo tamanho da operação. Ela começa pela clareza de quem quer ser percebida como.','Negócios locais vêm transformando produto em experiência ao tratar fotografia, atendimento, posicionamento e comunidade como parte da mesma linguagem.','Na DEU CAPA., esse movimento interessa porque mostra que visibilidade não é apenas aparecer: é ser lembrado com intenção.']},
gente:{category:'DEU GENTE',time:'4 MIN DE LEITURA',title:'Novos nomes, trajetórias e histórias para conhecer',subtitle:'Pessoas que constroem presença por meio do trabalho, da identidade e da capacidade de gerar conexão.',author:'Equipe DEU CAPA.',image:'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=1600&q=90',body:['Toda trajetória começa antes do reconhecimento. Há processos, tentativas e escolhas que normalmente ficam fora da fotografia final.','A proposta editorial da DEU CAPA. é mostrar também esse percurso: quem está criando, empreendendo, transformando e se tornando referência dentro da própria comunidade.','Mais do que números, procuramos histórias com personalidade, visão e algo relevante para compartilhar.']},
eventos:{category:'DEU AGENDA',time:'3 MIN DE LEITURA',title:'Os encontros que movimentam a cena criativa',subtitle:'Eventos ganham força quando deixam de ser apenas uma data e passam a criar memória, conexão e oportunidade.',author:'Equipe DEU CAPA.',image:'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1600&q=90',body:['Lançamentos, feiras, encontros culturais e experiências presenciais continuam sendo pontos importantes de conexão entre pessoas e marcas.','Quando bem apresentados, esses acontecimentos se transformam em conteúdo, relacionamento e memória compartilhada.','A agenda da DEU CAPA. nasce para destacar justamente os eventos que merecem atenção antes, durante e depois de acontecerem.']}
};
let spread=0,startX=0,lightboxIndex=0,galleryItems=[];
const $=s=>document.querySelector(s);
function menu(){const n=$('#siteNav');if(n)n.classList.toggle('open')}
function openReader(start=0){spread=start;const r=$('#reader');if(!r)return;r.classList.add('open');document.body.style.overflow='hidden';renderReader()}
function closeReader(){const r=$('#reader');if(!r)return;r.classList.remove('open');document.body.style.overflow=''}
function changeReader(dir){const total=Math.ceil(pages.length/2);spread=(spread+dir+total)%total;renderReader()}
function renderPage(el,p,index){if(!el||!p)return;el.className='readerPage '+(index%2===0?'image':'');if(index%2===0){el.style.backgroundImage=`url(${p.image})`;el.innerHTML=`<p class="eyebrow">${p.label}</p><h2>${p.title}</h2><span class="pageNo">PÁG. ${String(index+1).padStart(2,'0')}</span>`}else{el.style.backgroundImage='';el.innerHTML=`<p class="eyebrow">${p.label}</p><h2>${p.title}</h2><p>${p.text}</p><img src="${p.image}" alt="${p.title}" style="width:100%;height:46%;object-fit:cover;margin-top:15px"><span class="pageNo">PÁG. ${String(index+1).padStart(2,'0')}</span>`}}
function renderReader(){const l=spread*2,r=l+1;renderPage($('#readerLeft'),pages[l],l);renderPage($('#readerRight'),pages[r]||pages[0],r%pages.length);const c=$('#readerCount');if(c)c.textContent=`PÁGINAS ${l+1}–${Math.min(r+1,pages.length)} / ${pages.length}`}
function fullReader(){const b=$('#reader');if(b?.requestFullscreen)b.requestFullscreen()}
function prepareShare(){const type=$('#tipo')?.value||'Divulgação';const name=$('#nome')?.value||'';const contact=$('#contato')?.value||'';const msg=$('#mensagem')?.value||'';const text=`Olá! Quero aparecer na DEU CAPA.\nTipo: ${type}\nNome/Marca: ${name}\nContato: ${contact}\nMensagem: ${msg}`;navigator.clipboard?.writeText(text);const out=$('#formStatus');if(out)out.textContent='Texto da solicitação copiado. Agora você pode enviar pelo WhatsApp ou e-mail da revista.'}
function renderArticle(){const root=$('#articleRoot');if(!root)return;const id=new URLSearchParams(location.search).get('id')||'negocios';const a=articles[id]||articles.negocios;document.title=`${a.title} — DEU CAPA.`;root.innerHTML=`<article class="article"><header><p class="eyebrow">${a.category} • ${a.time}</p><h1>${a.title}</h1><p class="articleLead">${a.subtitle}</p><div class="articleMeta"><span>POR ${a.author.toUpperCase()}</span><button class="outline" onclick="shareArticle()">COMPARTILHAR ↗</button></div></header><figure><img src="${a.image}" alt="${a.title}"></figure><section class="articleBody">${a.body.map((p,i)=>i===0?`<p class="dropcap">${p}</p>`:`<p>${p}</p>`).join('')}<blockquote>Quem acontece, aparece — mas presença de verdade nasce quando existe história para sustentar a imagem.</blockquote>${a.body.slice(0,1).map(()=>'<p>A DEU CAPA. acompanha esse movimento com uma proposta visual, direta e conectada ao que está acontecendo agora.</p>').join('')}</section><div class="articleNext"><span>CONTINUE LENDO</span><a href="editorial.html">VER TODAS AS MATÉRIAS →</a></div></article>`}
function shareArticle(){if(navigator.share){navigator.share({title:document.title,url:location.href}).catch(()=>{})}else{navigator.clipboard?.writeText(location.href);alert('Link da matéria copiado.') }}
function initGallery(){galleryItems=[...document.querySelectorAll('[data-gallery]')];galleryItems.forEach((el,i)=>el.addEventListener('click',()=>openLightbox(i)))}
function openLightbox(i){lightboxIndex=i;const lb=$('#lightbox');if(!lb)return;lb.classList.add('open');lb.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';renderLightbox()}
function closeLightbox(){const lb=$('#lightbox');if(!lb)return;lb.classList.remove('open');lb.setAttribute('aria-hidden','true');document.body.style.overflow=''}
function changeLightbox(dir){if(!galleryItems.length)return;lightboxIndex=(lightboxIndex+dir+galleryItems.length)%galleryItems.length;renderLightbox()}
function renderLightbox(){const item=galleryItems[lightboxIndex];if(!item)return;const img=$('#lightboxImage'),title=$('#lightboxTitle'),count=$('#lightboxCount');if(img)img.src=item.dataset.image;if(title)title.textContent=item.dataset.title||'DEU CAPA.';if(count)count.textContent=`${lightboxIndex+1} / ${galleryItems.length}`}
document.addEventListener('keydown',e=>{if($('#lightbox')?.classList.contains('open')){if(e.key==='ArrowRight')changeLightbox(1);if(e.key==='ArrowLeft')changeLightbox(-1);if(e.key==='Escape')closeLightbox();return}if(!$('#reader')?.classList.contains('open'))return;if(e.key==='ArrowRight')changeReader(1);if(e.key==='ArrowLeft')changeReader(-1);if(e.key==='Escape')closeReader()});
document.addEventListener('DOMContentLoaded',()=>{renderArticle();initGallery();const r=$('#reader');if(r){r.addEventListener('touchstart',e=>startX=e.touches[0].clientX,{passive:true});r.addEventListener('touchend',e=>{const d=e.changedTouches[0].clientX-startX;if(Math.abs(d)>45)changeReader(d<0?1:-1)},{passive:true})}const lb=$('#lightbox');if(lb){lb.addEventListener('touchstart',e=>startX=e.touches[0].clientX,{passive:true});lb.addEventListener('touchend',e=>{const d=e.changedTouches[0].clientX-startX;if(Math.abs(d)>45)changeLightbox(d<0?1:-1)},{passive:true})}});