"use client";

import { useEffect, useMemo, useState } from "react";

type Page={id:string;label:string;title:string;body:string;imageUrl:string;layout:string};
type Edition={id:string;title:string;subtitle:string;status:"draft"|"published";coverImage:string;pages:Page[]};
const blankPage=(number:number):Page=>({id:crypto.randomUUID(),label:"EDITORIAL",title:`Nova página ${number}`,body:"Escreva aqui o conteúdo desta página.",imageUrl:"",layout:"editorial"});
const blankEdition=():Edition=>({id:crypto.randomUUID(),title:"Nova edição",subtitle:"Uma nova história começa aqui",status:"draft",coverImage:"",pages:[blankPage(1),blankPage(2)]});

export default function AdminEditor({userName}:{userName:string}){
  const [editions,setEditions]=useState<Edition[]>([]); const [activeId,setActiveId]=useState(""); const [selected,setSelected]=useState(0); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState(""); const [mobileNav,setMobileNav]=useState(false);
  const active=useMemo(()=>editions.find(e=>e.id===activeId),[editions,activeId]);
  useEffect(()=>{fetch("/api/editions").then(r=>r.json()).then(data=>{const list=Array.isArray(data)?data:[];setEditions(list);if(list[0])setActiveId(list[0].id)}).finally(()=>setLoading(false))},[]);
  const change=(patch:Partial<Edition>)=>setEditions(all=>all.map(e=>e.id===activeId?{...e,...patch}:e));
  const changePage=(patch:Partial<Page>)=>active&&change({pages:active.pages.map((p,i)=>i===selected?{...p,...patch}:p)});
  const createEdition=()=>{const item=blankEdition();setEditions(x=>[item,...x]);setActiveId(item.id);setSelected(0);setMobileNav(false)};
  const addPage=()=>{if(!active)return;change({pages:[...active.pages,blankPage(active.pages.length+1)]});setSelected(active.pages.length)};
  const duplicatePage=()=>{if(!active)return;const copy={...active.pages[selected],id:crypto.randomUUID(),title:`${active.pages[selected].title} — cópia`};const pages=[...active.pages];pages.splice(selected+1,0,copy);change({pages});setSelected(selected+1)};
  const removePage=()=>{if(!active||active.pages.length<=1)return;change({pages:active.pages.filter((_,i)=>i!==selected)});setSelected(Math.max(0,selected-1))};
  const move=(direction:number)=>{if(!active)return;const to=selected+direction;if(to<0||to>=active.pages.length)return;const pages=[...active.pages];[pages[selected],pages[to]]=[pages[to],pages[selected]];change({pages});setSelected(to)};
  const upload=async(file:File,target:"cover"|"page")=>{setMessage("Enviando imagem...");const form=new FormData();form.append("file",file);const response=await fetch("/api/upload",{method:"POST",body:form});const data=await response.json();if(!response.ok){setMessage(data.error||"Falha no envio");return}target==="cover"?change({coverImage:data.url}):changePage({imageUrl:data.url});setMessage("Imagem enviada")};
  const save=async(publish=false)=>{if(!active)return;setSaving(true);setMessage(publish?"Publicando edição...":"Salvando rascunho...");const payload={...active,status:publish?"published":active.status};const response=await fetch("/api/editions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});setSaving(false);if(response.ok){change({status:payload.status});setMessage(publish?"Edição publicada com sucesso":"Rascunho salvo")}else setMessage("Não foi possível salvar")};
  const erase=async()=>{if(!active||!confirm("Excluir esta edição e todas as páginas?"))return;await fetch(`/api/editions?id=${active.id}`,{method:"DELETE"});const rest=editions.filter(e=>e.id!==active.id);setEditions(rest);setActiveId(rest[0]?.id||"")};
  if(loading)return <div className="adminLoading">Preparando seu estúdio editorial…</div>;
  return <main className="adminShell">
    <aside className={mobileNav?"adminSide open":"adminSide"}><div className="adminLogo"><b>DEU CAPA.</b><span>EDITORIAL STUDIO</span></div><button className="newEdition" onClick={createEdition}>＋ NOVA EDIÇÃO</button><a className="requestsLink" href="/admin/solicitacoes">✦ SOLICITAÇÕES</a><a className="requestsLink" href="/admin/categorias">↻ PAINEL ROTATIVO</a><p className="sideLabel">SUAS EDIÇÕES</p><div className="editionList">{editions.map(e=><button key={e.id} className={e.id===activeId?"active":""} onClick={()=>{setActiveId(e.id);setSelected(0);setMobileNav(false)}}><span>{e.title}</span><small className={e.status}>{e.status==="published"?"PUBLICADA":"RASCUNHO"}</small></button>)}</div><a className="backSite" href="/">← Voltar para a revista</a></aside>
    <section className="adminMain"><header className="adminHeader"><button className="adminMenu" onClick={()=>setMobileNav(!mobileNav)}>☰</button><div><p>PAINEL ADMINISTRATIVO</p><h1>{active?.title||"Estúdio DEU CAPA."}</h1></div><div className="adminUser"><span>Olá, {userName}</span><a href="/signout-with-chatgpt?return_to=/">Sair</a></div></header>
      {!active?<div className="emptyAdmin"><span>✦</span><h2>Crie sua primeira edição</h2><p>Monte capas e páginas, envie suas fotos e publique quando estiver perfeito.</p><button className="primaryAdmin" onClick={createEdition}>CRIAR EDIÇÃO</button></div>:<>
      <div className="adminActions"><div className="statusLine"><i className={active.status}/>{active.status==="published"?"PUBLICADA":"RASCUNHO"}<span>{message}</span></div><button onClick={()=>save(false)} disabled={saving}>SALVAR</button><button className="publish" onClick={()=>save(true)} disabled={saving}>PUBLICAR EDIÇÃO ↗</button></div>
      <div className="editorGrid"><section className="formPanel"><div className="panelTitle"><span>01</span><div><p>INFORMAÇÕES</p><h2>Dados da edição</h2></div></div><label>Título<input value={active.title} onChange={e=>change({title:e.target.value})}/></label><label>Subtítulo<textarea value={active.subtitle} onChange={e=>change({subtitle:e.target.value})}/></label><label className="uploadBox">Capa da edição<input type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],"cover")}/>{active.coverImage?<img src={active.coverImage} alt="Capa"/>:<span>＋ Toque para enviar a capa</span>}</label><button className="danger" onClick={erase}>Excluir edição</button></section>
      <section className="pagesPanel"><div className="panelTitle"><span>02</span><div><p>PÁGINAS</p><h2>Organize a revista</h2></div><button onClick={addPage}>＋ ADICIONAR</button></div><div className="pageStrip">{active.pages.map((p,i)=><button key={p.id} className={i===selected?"active":""} onClick={()=>setSelected(i)}><span>{i+1}</span>{p.imageUrl?<img src={p.imageUrl} alt=""/>:<i>SEM FOTO</i>}<small>{p.label}</small></button>)}</div><div className="pageTools"><button onClick={()=>move(-1)}>← Mover</button><button onClick={()=>move(1)}>Mover →</button><button onClick={duplicatePage}>Duplicar</button><button onClick={removePage}>Excluir</button></div>{active.pages[selected]&&<div className="pageEditor"><label>Categoria<input value={active.pages[selected].label} onChange={e=>changePage({label:e.target.value.toUpperCase()})}/></label><label>Título<input value={active.pages[selected].title} onChange={e=>changePage({title:e.target.value})}/></label><label>Texto<textarea rows={5} value={active.pages[selected].body} onChange={e=>changePage({body:e.target.value})}/></label><label>Estilo<select value={active.pages[selected].layout} onChange={e=>changePage({layout:e.target.value})}><option value="editorial">Editorial clássico</option><option value="photo">Foto em destaque</option><option value="minimal">Minimalista</option></select></label><label className="smallUpload">Imagem da página<input type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],"page")}/><span>Enviar ou substituir imagem</span></label></div>}</section>
      <aside className="livePreview"><div className="panelTitle"><span>03</span><div><p>PRÉ-VISUALIZAÇÃO</p><h2>Como vai ficar</h2></div></div><div className={`previewPage ${active.pages[selected]?.layout||"editorial"}`} style={{backgroundImage:active.pages[selected]?.imageUrl?`url(${active.pages[selected].imageUrl})`:"none"}}><div className="previewShade"/><b>DEU CAPA.</b><small>{active.pages[selected]?.label}</small><h3>{active.pages[selected]?.title}</h3><p>{active.pages[selected]?.body}</p><em>PÁG. {String(selected+1).padStart(2,"0")}</em></div><p className="previewHelp">A prévia é atualizada enquanto você edita.</p></aside></div></>}
    </section>
  </main>;
}
