"use client";
import {useState} from "react";
const modules=[
 {icon:"✎",title:"Matérias",desc:"Escreva, revise, agende e publique matérias no site.",href:"/admin/materias",tag:"CONTEÚDO"},
 {icon:"▤",title:"Edições 3D",desc:"Monte capas, páginas e publique a revista interativa.",href:"/admin/edicoes",tag:"EDITORIAL"},
 {icon:"▧",title:"Fotos e galerias",desc:"Receba imagens, organize álbuns e controle os destaques visuais.",href:"/admin/galerias",tag:"MÍDIA"},
 {icon:"↻",title:"Painel rotativo",desc:"Categorias, ordem, links, visibilidade e velocidade.",href:"/admin/categorias",tag:"NAVEGAÇÃO"},
 {icon:"✦",title:"Solicitações",desc:"Receba propostas, organize contatos e aprove divulgações.",href:"/admin/solicitacoes",tag:"COMERCIAL"},
 {icon:"Aa",title:"Site e identidade",desc:"Edite slogan, chamada principal, textos, contato e redes sociais.",href:"/admin/site",tag:"MARCA"},
 {icon:"◷",title:"Agenda e eventos",desc:"Gerencie datas e divulgue os próximos acontecimentos.",href:"/admin/eventos",tag:"AGENDA"},
];
export default function ControlRoom({userName,stats}:{userName:string;stats:{editions:number;pages:number;requests:number;categories:number}}){const [menu,setMenu]=useState(false);return <main className="controlRoom"><aside className={menu?"open":""}><div className="crBrand"><b>DC.</b><span><strong>DEU CAPA.</strong><small>CONTROL ROOM</small></span></div><nav><a className="active" href="/admin">⌂ Visão geral</a><a href="/admin/materias">✎ Matérias</a><a href="/admin/edicoes">▤ Edições 3D</a><a href="/admin/galerias">▧ Fotos e galerias</a><a href="/admin/eventos">◷ Agenda e eventos</a><a href="/admin/categorias">↻ Painel rotativo</a><a href="/admin/solicitacoes">✦ Solicitações</a><a href="/admin/site">Aa Site e identidade</a></nav><div className="crBottom"><a href="/">← Ver revista</a><a href="/signout-with-chatgpt?return_to=/">Sair</a></div></aside><section className="crMain"><header><button onClick={()=>setMenu(!menu)}>☰</button><div><p>PAINEL CENTRAL</p><h1>Control Room</h1></div><span>Olá, {userName}</span><a href="/" target="_blank">VER SITE ↗</a></header><section className="crWelcome"><div><p>DEU CAPA. • EDITORIAL STUDIO</p><h2>Toda a revista.<br/><em>Um só lugar.</em></h2><span>Crie, organize, revise e publique toda a experiência editorial.</span></div><b>DC.</b></section><section className="crStats"><article><b>{stats.editions}</b><span>EDIÇÕES</span></article><article><b>{stats.pages}</b><span>MATÉRIAS E PÁGINAS</span></article><article><b>{stats.requests}</b><span>NOVAS PROPOSTAS</span></article><article><b>{stats.categories}</b><span>CATEGORIAS ATIVAS</span></article></section><div className="crTitle"><p>FERRAMENTAS</p><h2>O que você quer editar?</h2></div><section className="crModules">{modules.map(x=><a href={x.href} key={x.title}><small>{x.tag}</small><i>{x.icon}</i><h3>{x.title}</h3><p>{x.desc}</p><span>ABRIR FERRAMENTA ↗</span></a>)}</section></section></main>}
